import torch
import torch.nn.functional as F
import time



def loss_of_one_batch(batch, model, criterion, device, use_amp=False, 
                      model_type="unet",
                      is_eval = False):

    for key in batch.keys():
        if key == "name": continue
        batch[key] = batch[key].to(device, non_blocking=True)

    if model_type == "unet":
        pred_dict = model(batch["img"], mixed_precision=bool(use_amp))
    else:
        raise NotImplementedError()
        
    with torch.cuda.amp.autocast(enabled=bool(use_amp)):
        loss = criterion(pred_dict, batch) if criterion is not None else None

    return loss, pred_dict


def loss_of_one_batch_eval(batch, model, criterion, device, use_amp=False, cal_time=None):
    '''
    Perform model inference, resolution alignment, and metric computation.
    '''
    
    for key in batch.keys():
        if key == "name": continue
        batch[key] = batch[key].to(device, non_blocking=True)

    time_s = time.time()
    
    pred_dict = model(batch["img"], mixed_precision=bool(use_amp))
    
    time_e = time.time()
    time_second = (time_e - time_s)
    pred_dict["time"] = time_second

    # align Pred's resolution to GT 
    pred_dict = resize_pred_to_gt(batch, pred_dict)

    assert pred_dict["pts3d"].shape[1] == batch["pts3d"].shape[1] and pred_dict["pts3d"].shape[2] == batch["pts3d"].shape[2], "pred & gt's resolution misaligned!!"

    with torch.cuda.amp.autocast(enabled=bool(use_amp)):
        loss = criterion(pred_dict, batch) if criterion is not None else None

    return loss, pred_dict



def resize_pred_to_gt(data_dict, pred_dict):
    gt = data_dict["pts3d"]
    pred = pred_dict["pts3d"]
    img = data_dict["img"]  # image tensor with shape (B, 3, H, W)

    if gt.shape[1] != pred.shape[1] or gt.shape[2] != pred.shape[2]:
        B, H, W, L, C = pred.shape
        gt_H, gt_W = gt.shape[1], gt.shape[2]
        
        # Determine the scaling factor (the padded tensor was generated by scaling so that
        # the long edge becomes target size, then symmetric padding was applied)
        scale = max(gt_H / H, gt_W / W)
        new_H, new_W = int(H * scale), int(W * scale)
        
        # Permute to (B, L, C, H, W) so channels (L, C) are contiguous
        pred = pred.permute(0, 3, 4, 1, 2)
        # Flatten channel dimensions: shape (B, L * C, H, W)
        pred = pred.reshape(B, L * C, H, W)
        
        pred = F.interpolate(pred, size=(new_H, new_W), mode='bilinear', align_corners=False)
        
        # Reshape back to (B, L, C, new_H, new_W)
        pred = pred.reshape(B, L, C, new_H, new_W)
        # Permute back to (B, new_H, new_W, L, C)
        pred = pred.permute(0, 3, 4, 1, 2)

        crop_y = (new_H - gt_H) // 2
        crop_x = (new_W - gt_W) // 2
        pred = pred[:, crop_y:crop_y + gt_H, crop_x:crop_x + gt_W, :, :]
        pred_dict["pts3d"] = pred

        img = F.interpolate(img, size=(new_H, new_W), mode='bilinear', align_corners=False)
        img = img[:, :, crop_y:crop_y + gt_H, crop_x:crop_x + gt_W]
        data_dict["img"] = img

    return pred_dict
